### ISSUE TITLE
老大求助，能否帮忙加一个热键，可以根据选定内容自动生成标签吗？

### ISSUE THREAD

**Issue by jazzson** [b-yp/logseq-pinyin-match-tags#11]
老大，能否在插件中再加一个热键，可以根据选定内容来自动创建标签呢？ 

![QQ图片20230830132006](https://github.com/b-yp/logseq-pinyin-match-tags/assets/3415165/52c3beea-0573-42ad-971e-d064ceec5740)

**Comment by jazzson** [comment]
![QQ图片20230830132006](https://github.com/b-yp/logseq-pinyin-match-tags/assets/3415165/b874c2ea-57f9-4f2d-85bc-b198072dd9f1)

**Comment by b-yp** [comment]
Kapture 2023-09-15 at 20.46.45.mp4

**Comment by b-yp** [comment]
https://github.com/b-yp/logseq-pinyin-match-tags/assets/32813227/333ab5c9-211c-43f1-918f-1d31f918b1b9
