### ISSUE TITLE
老大帮忙，能否调整标签选择列表显示位置和筛选结果排序呢？

### ISSUE THREAD

**Issue by jazzson** [b-yp/logseq-pinyin-match-tags#13]
拼音标签插件大大简化了中文标签选择操作，不过还有两个小小不便，请老大帮助

![QQ截图20230920111950](https://github.com/b-yp/logseq-pinyin-match-tags/assets/3415165/81ec5ed2-8f94-408b-a90b-4c9e6d6bfbc6)

![QQ截图20230920112132](https://github.com/b-yp/logseq-pinyin-match-tags/assets/3415165/458437f1-4c7a-492f-8651-648ec86af2ec)

**Comment by b-yp** [comment]
1.5 版本中这两个功能已加
