### ISSUE TITLE
弹窗刷新按钮没有响应

### ISSUE THREAD

**Issue by jazzson** [b-yp/logseq-pinyin-match-tags#16]
标签选择按钮当弹出位置靠近顶部时候没有响应

![刷新没有响应](https://github.com/b-yp/logseq-pinyin-match-tags/assets/3415165/5990b944-81fa-42f3-bdb3-4013fb4e6c5c)

**Comment by b-yp** [comment]
已修复 https://github.com/b-yp/logseq-pinyin-match-tags/pull/17
