### ISSUE TITLE
请帮助，无序列列中标签选中后无法插入

### ISSUE THREAD

**Issue by jazzson** [b-yp/logseq-pinyin-match-tags#20]
无序列列中标签选中后无法插入，会加入 logseq.order-list ... 附加内容，导致标签插入事变

请老大帮忙哈 

![QQ图片20231024113525](https://github.com/b-yp/logseq-pinyin-match-tags/assets/3415165/7b1f6876-8d77-4138-87c7-47bcddb945a8)

**Comment by b-yp** [comment]
这个问题修复了
