### ISSUE TITLE
如何优化性能, 大概有2300个tag

### ISSUE THREAD

**Issue by leeyaunlong** [b-yp/logseq-pinyin-match-tags#8]
如何优化性能, 大概有2300个tag
触发一次要等大约5-10秒.
一次也还好, 每次都要等.
能不能加个cache什么的?

**Comment by b-yp** [comment]
> 如何优化性能, 大概有2300个tag
> 触发一次要等大约5-10秒.
> 一次也还好, 每次都要等.
> 能不能加个cache什么的?

可以加的，之前是考虑到最新创建的 tag 查询不到，所以每次触发都会全查一遍，小弟想办法优化一下
用官方的 # 插入 tag 会很快对吧

**Comment by leeyaunlong** [comment]
> > 如何优化性能, 大概有2300个tag
> > 触发一次要等大约5-10秒.
> > 一次也还好, 每次都要等.
> > 能不能加个cache什么的?
> 
> 可以加的，之前是考虑到最新创建的 tag 查询不到，所以每次触发都会全查一遍，小弟想办法优化一下 用官方的 # 插入 tag 会很快对吧

用官方的很快. 
BTW 开始打错了, 不是2千tag是有2万个tag,

**Comment by b-yp** [comment]
> > > 如何优化性能, 大概有2300个tag
> > > 触发一次要等大约5-10秒.
> > > 一次也还好, 每次都要等.
> > > 能不能加个cache什么的?
> > 
> > 可以加的，之前是考虑到最新创建的 tag 查询不到，所以每次触发都会全查一遍，小弟想办法优化一下 用官方的 # 插入 tag 会很快对吧
> 
> 用官方的很快. 
> BTW 开始打错了, 不是2千tag是有2万个tag,

😲 卧槽，那确实多，这么多每次查询肯定很慢的，小弟想想办法

**Comment by b-yp** [comment]
发了个新版本，新增了缓存，如果新加的标签搜索不到需要点一下 “刷新” 按钮

**Comment by leeyaunlong** [comment]
> 发了个新版本，新增了缓存，如果新加的标签搜索不到需要点一下 “刷新” 按钮

比之前快一点.每次查询还是要5s+.

你是不是只存了keyword, 而不是存的 keyword+pinyin ?
存 keyword+pinyin 应该会更快把

**Comment by b-yp** [comment]
我把你这 2 万个 tag 存起来了，避免每次都查，你试试点击刷新按钮，大概几秒能看到结果

**Comment by leeyaunlong** [comment]
> 我把你这 2 万个 tag 存起来了，避免每次都查，你试试点击刷新按钮，大概几秒能看到结果

之前10s+ , 现在5s 每次.

**Comment by b-yp** [comment]
现在默认弹窗是不会去查所有 tag 的，直接用存起来的，应该会比较快，缺点是新增的 tag 查不到，点击刷新按钮才是查询当前所有的  tag， 包括新增的， 所以如果不点刷新按钮没有那么慢吧，应该不到 1s  ?  ，我也没有整那么多数据测试过 😂

**Comment by leeyaunlong** [comment]
> 现在默认弹窗是不会去查所有 tag 的，直接用存起来的，应该会比较快，缺点是新增的 tag 查不到，点击刷新按钮才是查询当前所有的 tag， 包括新增的， 所以如果不点刷新按钮没有那么慢吧，应该不到 1s ? ，我也没有整那么多数据测试过 😂

你只存了tag啊, 2w个tag是cache了 还要算2w次 拼音把? 这也要时间啊.

**Comment by leeyaunlong** [comment]
> 现在默认弹窗是不会去查所有 tag 的，直接用存起来的，应该会比较快，缺点是新增的 tag 查不到，点击刷新按钮才是查询当前所有的 tag， 包括新增的， 所以如果不点刷新按钮没有那么慢吧，应该不到 1s ? ，我也没有整那么多数据测试过 😂

你只存了tag啊, 2w个tag是cache了 还要算2w次 拼音把? 这也要时间啊.

**Comment by b-yp** [comment]
不需要保存拼音，匹配算法使用的开源库，库内部会维护拼音，这个库匹配 3000 条数据都是在 10ms 以内
